package com.service.nombre.login.models.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "usuarios")
public class Usuario {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String usuarioId;
    @DynamoDBAttribute
    private String username;
    @DynamoDBAttribute
    private String password;
    @DynamoDBAttribute
    private String nombre;
    @DynamoDBAttribute
    private String apellido;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String telefono;
}
